name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  check-applications:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.22.1', '1.23.1' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}
      - run: go test
      - run: go run math.go